version: "3.7"

services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      # - MENU_VERSION=2.0.47 # optional, sets menus version, unset uses latest
    volumes:
      -  ${APP_DATA_DIR}/data/config:/config # optional
      -  ${APP_DATA_DIR}/data/assets:/assets # optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:8080 #optional
    restart: unless-stopped